In [ ]:
!pip install yfinance
!pip install pyportfolioopt

# importación de librerías necesarias
import math
import numpy as np
import pandas as pd
import yfinance as yf
from pypfopt.efficient_frontier import EfficientFrontier

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 1.9 MB/s eta 0:00:00


In [ ]:
portfolio = ['TSM', 'AAL', 'KWHIY', 'BABA', 'KO', 'PFE']
# TSMC, American Airlines, Kawasaki, Alibaba, Coca-Cola, Pfizer

# Restricción máxima de activos en portafolio:
if len(portfolio) > 10:
  raise Exception ('El número máximo de activos en el portafolio es de 10')
else:
  # Se cumple la restricción:

  stock_prices = pd.DataFrame()
  stock_returns = pd.DataFrame()

  for x in portfolio:
    stock = yf.Ticker(x)
    close_price = stock.history(period='5y')['Close']

    # Se insertan datos en stock_prices y stock_returns
    stock_prices = pd.concat([stock_prices, close_price], axis=1)
    # Con pct_change() obtenemos los rendimientos (cambio porcentual)
    stock_returns = pd.concat([stock_returns, close_price.pct_change()], axis=1)

# Asignamos nombre de acciones a las columnas de cada DataFrame

stock_prices.columns = portfolio
stock_returns.columns = portfolio

# Eliminamos valores nulos de las columnas con dropna()
# (El primer valor de rendimiento es nulo)

stock_returns = stock_returns.dropna()

# Ver los datos generados:
print('Precios diarios, últimos 5 años (máximo)')
display(stock_prices)
print('Rendimientos diarios, últimos 5 años (máximo)')
display(stock_returns)
#Ejecutamos

Precios diarios, últimos 5 años (máximo)


TSM        AAL  KWHIY        BABA         KO  \
2018-09-24 00:00:00-04:00  39.650723  41.198277  11.60  163.160004  39.413818   
2018-09-25 00:00:00-04:00  39.014755  40.050064  11.65  164.250000  39.080162   
2018-09-26 00:00:00-04:00  39.103085  40.275780  11.61  165.399994  39.225590   
2018-09-27 00:00:00-04:00  39.535892  40.727211  11.38  166.320007  39.362480   
2018-09-28 00:00:00-04:00  39.005920  40.560375  11.38  164.759995  39.516483   
...                              ...        ...    ...         ...        ...   
2023-09-18 00:00:00-04:00  88.830002  13.110000  10.48   87.019997  58.299999   
2023-09-19 00:00:00-04:00  88.169998  13.190000  10.42   87.110001  58.180000   
2023-09-20 00:00:00-04:00  87.290001  13.060000  10.42   85.739998  58.439999   
2023-09-21 00:00:00-04:00  85.360001  13.060000  10.27   84.110001  57.540001   
2023-09-22 00:00:00-04:00  85.639999  12.900000  10.22   88.300003  57.599998   

                                 PFE  
2018-09-24 00:00:00-04:00  34.622456  
2018-09-25 00:00:00-04:00  34.512108  
2018-09-26 00:00:00-04:00  34.425411  
2018-09-27 00:00:00-04:00  34.598808  
2018-09-28 00:00:00-04:00  34.732792  
...                              ...  
2023-09-18 00:00:00-04:00  33.639999  
2023-09-19 00:00:00-04:00  33.990002  
2023-09-20 00:00:00-04:00  33.619999  
2023-09-21 00:00:00-04:00  32.849998  
2023-09-22 00:00:00-04:00  32.689999  

[1258 rows x 6 columns]

Rendimientos diarios, últimos 5 años (máximo)


TSM       AAL     KWHIY      BABA        KO  \
2018-09-25 00:00:00-04:00 -0.016039 -0.027870  0.004310  0.006681 -0.008465   
2018-09-26 00:00:00-04:00  0.002264  0.005636 -0.003433  0.007001  0.003721   
2018-09-27 00:00:00-04:00  0.011068  0.011209 -0.019810  0.005562  0.003490   
2018-09-28 00:00:00-04:00 -0.013405 -0.004096  0.000000 -0.009380  0.003912   
2018-10-01 00:00:00-04:00  0.011323 -0.041616 -0.016696 -0.016752  0.000866   
...                             ...       ...       ...       ...       ...   
2023-09-18 00:00:00-04:00 -0.004706 -0.015026 -0.002854 -0.000574  0.006213   
2023-09-19 00:00:00-04:00 -0.007430  0.006102 -0.005725  0.001034 -0.002058   
2023-09-20 00:00:00-04:00 -0.009981 -0.009856  0.000000 -0.015727  0.004469   
2023-09-21 00:00:00-04:00 -0.022110  0.000000 -0.014395 -0.019011 -0.015400   
2023-09-22 00:00:00-04:00  0.003280 -0.012251 -0.004869  0.049816  0.001043   

                                PFE  
2018-09-25 00:00:00-04:00 -0.003187  
2018-09-26 00:00:00-04:00 -0.002512  
2018-09-27 00:00:00-04:00  0.005037  
2018-09-28 00:00:00-04:00  0.003872  
2018-10-01 00:00:00-04:00  0.004538  
...                             ...  
2023-09-18 00:00:00-04:00 -0.012621  
2023-09-19 00:00:00-04:00  0.010404  
2023-09-20 00:00:00-04:00 -0.010886  
2023-09-21 00:00:00-04:00 -0.022903  
2023-09-22 00:00:00-04:00 -0.004871  

[1257 rows x 6 columns]

In [ ]:
# Rendimiento esperado de activos
expected_stock_returns = []

# Riesgo individual de activos
individual_stock_risk = []

for x, y in stock_returns.iteritems():
  # En cada iteración se obtiene el rendimiento esperado y riesgo individual
  # de cada activo (media y desviación estándar)
  expected_stock_returns.append(y.mean())
  individual_stock_risk.append(y.std())

# Tratamiendo de datos para ser operados como vectores más adelante
expected_stock_returns = np.array(pd.DataFrame(expected_stock_returns))
individual_stock_risk = np.array(pd.DataFrame(individual_stock_risk))

# Ver datos generados:
print('Rendimientos esperados')
print(expected_stock_returns)
print('Riesgo individual')
print(individual_stock_risk)

Rendimientos esperados
[[ 8.66362253e-04]
 [-1.80906244e-04]
 [ 2.79690744e-04]
 [-2.24087645e-05]
 [ 3.93580510e-04]
 [ 9.30968004e-05]]
Riesgo individual
[[0.02257389]
 [0.03904267]
 [0.02755808]
 [0.0309266 ]
 [0.01350063]
 [0.01669027]]


<ipython-input-4-fdbb3622a559>:7: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for x, y in stock_returns.iteritems():


In [ ]:
# Para obtener matriz de covarianza:

stock_returns_cov_matrix = np.array(stock_returns.cov())

# Ver datos generados:

print('Matriz de covarianza de rendimientos de activos')
display(stock_returns_cov_matrix)

Matriz de covarianza de rendimientos de activos


array([[5.09580522e-04, 2.85545785e-04, 1.41440935e-04, 2.67979208e-04,
        7.92173652e-05, 6.36118653e-05],
       [2.85545785e-04, 1.52433032e-03, 2.07289464e-04, 3.00524883e-04,
        1.79038395e-04, 9.96016767e-05],
       [1.41440935e-04, 2.07289464e-04, 7.59448011e-04, 1.25727128e-04,
        7.30930005e-05, 5.75480461e-05],
       [2.67979208e-04, 3.00524883e-04, 1.25727128e-04, 9.56454406e-04,
        5.90052931e-05, 5.44374895e-05],
       [7.92173652e-05, 1.79038395e-04, 7.30930005e-05, 5.90052931e-05,
        1.82266973e-04, 9.78076232e-05],
       [6.36118653e-05, 9.96016767e-05, 5.75480461e-05, 5.44374895e-05,
        9.78076232e-05, 2.78564973e-04]])

In [ ]:
# Creación de portafolio subóptimo

def suboptimal_investment_portfolio(portfolio):
  suboptimal_portfolio = []

  # Iteramos y asignamos proporción igualitaria de inversión a cada
  # activo del portafolio.
  for x in portfolio:
    suboptimal_portfolio.append(1/len(portfolio))

  suboptimal_portfolio = np.array(suboptimal_portfolio)
  return suboptimal_portfolio

# Ejecutamos la función recién creada, pasando el portafolio inicial como argumento
suboptimal_portfolio = suboptimal_investment_portfolio(portfolio)
# Tratmiento en numpy para operaciones posteriores
suboptimal_portfolio = np.expand_dims(suboptimal_portfolio, axis=0)

# Ver los datos generados:
print('Portafolio subóptimo:')
print(suboptimal_portfolio)

Portafolio subóptimo:
[[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]]


In [ ]:
# Rendimiento esperado del portafolio subóptimo
expected_subopt_return = np.matmul(suboptimal_portfolio, expected_stock_returns)

# Varianza del portafolio subóptimo
subopt_portfolio_var = np.matmul(suboptimal_portfolio, \
                                 np.matmul(stock_returns_cov_matrix, suboptimal_portfolio.transpose()))

# Riesgo del portafolio subóptimo
subopt_portfolio_risk = math.sqrt(subopt_portfolio_var)

# Ver datos generados:
print('Portafolio subóptimo')
print(f'Rendimiento esperado: {expected_subopt_return*100}')
print(f'Varianza: {subopt_portfolio_var*100}')
print(f'Riesgo del protafolio: {subopt_portfolio_risk*100}')

Portafolio subóptimo
Rendimiento esperado: [[0.02382359]]
Varianza: [[0.02331773]]
Riesgo del protafolio: 1.5270142911997444


In [ ]:
### OPTIMIZACION DE MARKOWITZ ###
ef = EfficientFrontier(expected_stock_returns, stock_returns_cov_matrix, weight_bounds=(0,1))
ratios = ef.min_volatility()
cleaned_ratios = pd.Series(ratios)
cleaned_ratios.index = portfolio

optimal_portfolio = np.expand_dims(cleaned_ratios, axis=0)

# Rendimiento esperado
opt_portfolio_expected_return = np.matmul(optimal_portfolio, expected_stock_returns)

# Varianza del portafolio
opt_portfolio_var = np.matmul(optimal_portfolio, \
                              np.matmul(stock_returns_cov_matrix, optimal_portfolio.transpose()))

# Riesgo del portafolio
opt_portfolio_risk = math.sqrt(opt_portfolio_var)

# Ver datos obtenidos y Portafolio Óptimo de Markowitz:
print('PORTAFOLIO ÓPTIMO DE MARKOWITZ:')
print(f'Rendimiento esperado: {opt_portfolio_expected_return*100}')
print(f'Varianza del portafolio: {opt_portfolio_var*100}')
print(f'Riesgo del portafolio: {opt_portfolio_risk*100}')

print('\n\nDel 100% de tu capital, el modelo sugiere\
invertir las siguientes proporciones en cada activo:')
display(cleaned_ratios*100)

PORTAFOLIO ÓPTIMO DE MARKOWITZ:
Rendimiento esperado: [[0.03328439]]
Varianza del portafolio: [[0.01345973]]
Riesgo del portafolio: 1.1601607284670972


Del 100% de tu capital, el modelo sugiereinvertir las siguientes proporciones en cada activo:


TSM      10.171038
AAL       0.000000
KWHIY     8.095808
BABA      5.582114
KO       50.731304
PFE      25.419736
dtype: float64